### ISSUE TITLE
Pulling out Julia's patched LLVM

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/julia-feedstock#25]
One thing we might want to start considering is pulling out Julia's patched LLVM portion as a separate package. Building LLVM alone takes a lot of time. As such we may start encountering difficulties building Julia outside of CircleCI where time limits are more stringent or for later versions of Julia.

If we can create a separate package for Julia's LLVM build possibly using the `llvmdev` package and an `llvm_variant`, we should be able to rely on that package for the build (and run?). Doing this should allow us to cutdown the build time here and also draw on the expertise we have here at conda-forge. This will require coordination with the @conda-forge/llvmdev team and @SylvainCorlay's guidance in particular as he developed the `llvm_variant` system.

**Comment by mingwandroid** [comment]
I think mutex variants should be avoided here. We're basing our macOS compilers on llvm too, so what happens then? And back when Rust required a differently patched LLVM?

Do you have any links as to why Julia need to patch LLVM? Please if, you can, link me to the patches.

**Comment by jakirkham** [comment]
This would be a good question for @tkelman.

**Comment by mingwandroid** [comment]
Static linking is a far better alternative than variants here IMHO. But using the same package for everything is far better than that, even if it means some hacks to make that work.

**Comment by mingwandroid** [comment]
And CI time is one of the worst reasons I can imagine for baking technical debt into your ecosystem.

**Comment by jakirkham** [comment]
Not sure what to say @mingwandroid. We have no way to extend the CI time. We also lack any other build resources that could be used. Do you have some alternatives? Otherwise bad reason or not, we are stuck breaking things up like this.

That all being said, LLVM is a separate thing from Julia. Seems pretty reasonable to me that they be broken up into two different packages, no?

**Comment by mingwandroid** [comment]
The *split* is not the issue here. It's having a *different* LLVM for Julia than for the rest of the ecosystem (unless it's purely static, which is still pretty awful). Mutex variants probably the most blunt and destructive tools in our toolbox. I'd rather people built Julia on their own computers than we create package islands.

**Comment by jakirkham** [comment]
So our `llvmdev` package is static FWIR. The variant is there to select different patched builds. IOW I don't think we are disagreeing on this.

Though I do remember there was some concern last year as to whether a static LLVM would work for Julia. I'm not sure if that is still the case or not. I didn't see any obvious indications that our Julia package included LLVM libraries. So maybe things have changed? I could have overlooked something though.

**Comment by mingwandroid** [comment]
I'm +1 on splitting, I'd like to build a whole range of tools and languages from a single llvm tree, much like we do [here](https://github.com/AnacondaRecipes/aggregate/blob/master/llvm-compilers-feedstock/recipe/meta.yaml) but please, let's consider trying to work on the reasons for needing distinct forks instead of accepting them as immutable facts of life.

**Comment by tkelman** [comment]
1. Julia needs a set of patches to LLVM to work correctly
2. Almost all of these have been or are in the (sometimes slow) process of being upstreamed, but
3. By the time all patches get upstreamed (if that ever happens, new bugfixes/features/performance patches get added constantly), the version of LLVM that includes them has a very different API than the rest of what Julia was written against

This is why so many projects have to effectively fork LLVM. The combination of baseline release plus necessary patches that works and gets tested for Julia isn't going to be tested and usable against every other piece of software in the world that uses LLVM - this is why distros have to maintain multiple LLVM package versions in parallel.

We prefer using a shared library of LLVM so that we can dynamically utilize parts of the API that may get tree-shaken by a static link, if the base Julia library doesn't call them but runtime packages like Cxx.jl or CUDAnative.jl will want to. This does cause some issues with version mismatches with things like gl libraries, ideally shared library builds of llvm would have an option to rename or namespace all the exported library symbols - we do something similar in our default builds of blas and lapack which use 64 bit integers.

**Comment by tkelman** [comment]
>  We have no way to extend the CI time

If you ask nicely, the CI services will usually increase your timeout. But it could eat up more queue time if you aren't careful about hung builds. Best would be if it were yml configurable per repo and service, I opened that feature request with appveyor long ago but no luck so far.

**Comment by SylvainCorlay** [comment]
**Note:** the cling folks are also upstreaming their patches as they go.

**Comment by jakirkham** [comment]
We asked Travis CI about extending the time limit before and they said they could give us more time, but would cut the number of concurrent jobs. After discussion at our dev meeting, we decided against this option as the extension in time was small and the loss in concurrency was quite significant. We already struggle with concurrency on Travis CI now.

**Comment by ViralBShah** [comment]
I suggest using the upstream binaries that we provide in #41. That would solve travis issues too that arise out of building llvm.

**Comment by tkelman** [comment]
> ideally shared library builds of llvm would have an option to rename or namespace all the exported library symbols

It's a bit of a hassle for me to find more specific links to these things now, but this got implemented. Stop statically linking llvm here. Variants don't need to be mutually exclusive if they're namespaced.
